sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

language: python

python:
  - "3.5"
  - "3.6"

before_install:
  - docker volume create xqa-message-broker
  - docker pull jameshnsears/xqa-message-broker
  - docker run -d --net="host" --name="xqa-message-broker" -p 127.0.0.1:5672:5672 jameshnsears/xqa-message-broker
  - sleep 10
  - docker logs xqa-message-broker

  - sudo apt-get remove cmake
  - sudo apt-get install -y gcc cmake-curses-gui uuid-dev libssl-dev libsasl2-2 libsasl2-dev swig python-dev python3-dev ruby-dev libperl-dev

  - pwd
  - pip install -r requirements.txt

script:
  - export PYTHONPATH=/home/travis/build/jameshnsears/xqa-shard/src:$PYTHONPATH
  - coverage run --omit */site-packages/*,*/virtualenv/*,*/org/basex/* src/xqa/shard.py > shard.log &
  - python test/integration/shard_test.py > shard_test.log

  - cat shard.log
  - cat shard_test.log

  - grep "sha256=f1bcf55ede4b89962b411213bcbd1918f3e1659d786c1aff20fd5bd89fbcae70" shard.log

  - grep "sha256(body)=f1bcf55ede4b89962b411213bcbd1918f3e1659d786c1aff20fd5bd89fbcae70" shard_test.log
  - grep "xquery_response" shard_test.log | grep "body=b"


  - mkdir coverage
  - mv .coverage coverage/.coverage.0

after_success:
  - pytest --flake8 --cov-report term-missing --cov=. test/storage_service_test.py
  - mv .coverage coverage/.coverage.1
  - cd coverage
  - coverage combine
  - codecov --token=54978e9f-f156-442a-a471-4f676d8ff923
  - COVERALLS_REPO_TOKEN=gNQsMIHlJD0YeTwwcdM1UVEh4lJxUV77t coveralls
