sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

language: python

git:
  depth: false

python:
  - "3.6"

before_install:
  - docker-compose pull xqa-message-broker

  - pip install --upgrade pip
  - pip install -r requirements.txt
  - flake8 src test

script:
  - export PYTHONPATH=src:$PYTHONPATH
  - pytest -s --cov-report term-missing --cov=.

after_success:
  - COVERALLS_REPO_TOKEN=59P9elXG606x9EM64dxWGQ6i8XAZ1yFNO coveralls

after_failure:
  - docker images
  - docker ps -a
  - docker logs xqa-ingest
  - docker logs xqa-message-broker
  - docker logs xqa-ingest-balancer
  - docker logs xqa-shard
