version: '3'

services:
  xqa-shard:
    build: .
    image: xqa-shard
    container_name: xqa-shard
    command: ["-message_broker_host", "xqa-message-broker"]
    ports:
      - 1984
    depends_on:
      - xqa-message-broker
    networks:
      - xqa

volumes:
  xqa-message-broker:

networks:
  xqa:
